window.LOCAL_STORY_SCENES = [
  {
    id: 'atrium-opening-local',
    stageId: 'atrium',
    trigger: 'beforeEncounter',
    title: 'Opening scene',
    sourceUrl: 'https://tiphereth.zasz.su/episodes/1_1_1/',
    backgroundUrl: null,
    requiredFlags: [],
    speakerIds: {
      '???': 'angela',
      '??? (Intruder)': 'roland',
      'Roland (Intruder)': 'roland',
    },
    dialogue: [
      { speaker: '???', text: 'I still cannot leave this place...' },
      { speaker: '???', text: 'Even at the end of all this, I cannot be free...' },
      { speaker: '???', text: 'Am I not allowed to have a dream that is beyond my means...?' },
      { speaker: '??? (Intruder)', text: 'Damn it... The Purple Tear...' },
      { speaker: '??? (Intruder)', text: "Can't believe this is how she handled it..." },
      { speaker: '??? (Intruder)', text: "What the hell happened? What's with all this smoke?" },
      { speaker: '??? (Intruder)', text: "Sigh... Guess I'll have to trust her..." },
      { speaker: '???', text: "...I'll only say this once." },
      { speaker: '???', text: "I despise verbose and roundabout speech that doesn't get straight to the point." },
      { speaker: '???', text: "So don't try to get wordy. Just answer my questions." },
      { speaker: '???', text: "You don't get to question me, either." },
      { speaker: '???', text: 'Where did you come from, how did you enter this place, and for what purpose?' },
      { speaker: '??? (Intruder)', text: 'Well, who are you to...' },
      { speaker: '??? (Intruder)', text: "Ugh, boy... I'm suddenly getting all nauseous...", expression: 'tired' },
      { speaker: '??? (Intruder)', text: 'AHHHHHH!!! My leg!!!', expression: 'injured' },
      { speaker: '???', text: 'I warned you, and you crossed the line. Let me ask you one more time.' },
      { speaker: '???', text: 'Where did you come from, how did you enter this place, and for what purpose?' },
      { speaker: '??? (Intruder)', text: "...I was just walking around, and ended up here before I even realized it. I have no idea how I got here. Dammit, blood's gushing outta my right leg... I swear I wasn't trying to trespass, I don't even know where this is." },
      { speaker: '??? (Intruder)', text: 'I woke up around 1 PM and started walking around the streets of District 13. Since I was just out and about, I figured I could go wherever I wanted, so I decided to drop by HamHamPangPang. Heard they served a weekly special sandwich.' },
      { speaker: '??? (Intruder)', text: 'Anyway, I had bills to pay, got no jobs, had to make a living somehow as a one-man Offi-' },
      { speaker: '??? (Intruder)', text: 'ARGHHHHH!!!!!', expression: 'injured' },
      { speaker: '???', text: "You dragged on too long. I'll be taking your left arm and left leg next." },
      { speaker: '???', text: "You have no purpose, and you don't even know how you got here... Just who are you?" },
      { speaker: '??? (Intruder)', text: "Just an ordinary Fixer who's hit rock bottom. What the hell is this place? And who are you?" },
      { speaker: '??? (Intruder)', text: 'Grrhhhrghh!!! Come on, taking two limbs at once is cheating...', expression: 'injured' },
      { speaker: '???', text: "I'm the one asking questions. Your name?" },
      { speaker: 'Roland (Intruder)', text: 'Roland...' },
      { speaker: '???', text: "Good. Welcome to the Library. We've yet to serve any guests, but then you suddenly appeared out of nowhere." },
      { speaker: '???', text: 'It took me quite a bit of effort designing this Library to ensure that no uninvited guest could enter, you see.' },
      { speaker: 'Roland (Intruder)', text: "...Dammit, these limbs were all I had... I don't have any cash or mortgages to get new ones anymore..." },
      { speaker: '???', text: "Seems he's fainted." },
    ],
  },
];